### ISSUE TITLE
Thr result about hsic_gam has wrong?

### ISSUE THREAD

**Issue by 945716994** [amber0309/HSIC#4]
The testStat maybe means test statistic?
The thresh maybe means test threshold for level alpha test?
![image](https://user-images.githubusercontent.com/36669447/133814107-b3b9fec9-c4e0-4fb5-a279-aa80fd69b306.png)

**Comment by amber0309** [comment]
Corrected and thanks a lot for spotting this typo.

**Comment by 945716994** [comment]
![image](https://user-images.githubusercontent.com/36669447/135580549-68ffe0a1-cf07-4be6-9ead-4f5713907534.png)
testStat > thresh -> x and y are independent? or just like you write that means x and y are not independent?

**Comment by amber0309** [comment]
testStat > thresh -> x and y are NOT independent
